### PR TITLE
fix: flickers child screen when resizing window

### PR DESCRIPTION
**Pull request by letrungdo**
fix issue: https://github.com/rustdesk/rustdesk/issues/8505

### CODE REVIEW

**Comment by letrungdo** [comment]
> Before:
[before.webm](https://github.com/user-attachments/assets/46463133-efbf-4191-8674-ff6f3809b978)

> After:
[after.webm](https://github.com/user-attachments/assets/26594bbc-3967-4b2f-9bdc-74e356e51251)

**Comment by rustdesk** [comment]
@fufesou test please

**Comment by letrungdo** [comment]
This pr may affect your old bug: https://github.com/rustdesk-org/rustdesk_desktop_multi_window/pull/11
However, you can fix it by writing an additional setBackgroundColor function and setting it to black when creatingWindow https://github.com/rustdesk-org/rustdesk_desktop_multi_window/commit/b487a8bb4ac18783082a39e24e411dc295a4537d

After initState of the screen in WidgetsBinding.instance.addPostFrameCallback, you call setBackgroundColor(Colors.transparent);

**Comment by fufesou** [comment]
> This pr may affect your old bug: https://github.com/rustdesk-org/rustdesk_desktop_multi_window/pull/11

Yes.
I cannot reproduce [before.webm](https://github.com/user-attachments/assets/46463133-efbf-4191-8674-ff6f3809b978) easily.

> However, you can fix it by writing an additional setBackgroundColor function and setting it to black when creatingWindow https://github.com/rustdesk-org/rustdesk_desktop_multi_window/commit/b487a8bb4ac18783082a39e24e411dc295a4537d

Agree.

**Comment by letrungdo** [comment]
@fufesou You can reproduce on a virtual machine or a low-end machine or your screen renders a lot of widgets

**Comment by fufesou** [comment]
> However, you can fix it by writing an additional setBackgroundColor function and setting it to black when creatingWindow https://github.com/rustdesk-org/rustdesk_desktop_multi_window/commit/b487a8bb4ac18783082a39e24e411dc295a4537d

@letrungdo  Hi, I've tested `setBackgroundColor()`, it works fine.

But I can't find the commit in this repo. Where do you find the commit?

I can also see `setBackgroundColor()` is possible for Linux.

https://github.com/leanflutter/window_manager/blob/73c39f406c56de682b6c34d8cc744cecdcb471bb/linux/window_manager_plugin.cc#L868C33-L868C51

**Comment by letrungdo** [comment]
@fufesou You can see the latest commit in this branch: https://github.com/rustdesk-org/rustdesk_desktop_multi_window/compare/master...guide-inc-org:guide-flutter_desktop_multi_window:sbi-fx-pc

**Comment by rustdesk** [comment]
@letrungdo we are upgrading to flutter 3.24 (this version fix some windows blank screen issues, https://github.com/rustdesk/rustdesk/issues/6756#issuecomment-2371418990), but blocked by https://github.com/flutter/flutter/issues/155685, have you ever done similar job?

**Comment by letrungdo** [comment]
@rustdesk I also tried to upgrade to flutter 3.24 but had the same problem. I will investigate when I have time.

**Pull request merged**
